void main() {
  try{
    int numero = 10;
    int? numero2;

  print(numero / numero2!);
  }catch(e){
    print("Ocurrio una excepcion");
  }
}
